In [1]:
library("RSQLite")
library("DBI")
library("data.table")
library("sqldf")
library("dplyr")

Loading required package: gsubfn
Loading required package: proto
Could not load tcltk.  Will use slower R code instead.
------------------------------------------------------------------------------
data.table + dplyr code now lives in dtplyr.
Please library(dtplyr)!
------------------------------------------------------------------------------

Attaching package: ‘dplyr’

The following objects are masked from ‘package:data.table’:

    between, first, last

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [3]:
install.packages("dplyr")

Warning message in install.packages("dplyr"):
“installation of package ‘dplyr’ had non-zero exit status”Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

In [2]:
con=dbConnect(drv=RSQLite::SQLite(),dbname="/home/naina/Downloads/database.sqlite")

In [3]:
tables=dbListTables(con)

In [4]:
print(tables)

[1] "Country"           "League"            "Match"
[4] "Player"            "Player_Attributes" "Team"
[7] "Team_Attributes"   "sqlite_sequence"

In [5]:
p1=dbGetQuery(con,'select Player.player_name, Player.player_api_id,max(Player_Attributes.overall_rating)AS overall_rating,(max(Player_Attributes.gk_diving)+max(Player_Attributes.gk_handling)+max(Player_Attributes.gk_kicking)+max(Player_Attributes.gk_positioning)+max(Player_Attributes.gk_reflexes)) AS gk_ratings from Player, Player_Attributes where Player.player_api_id=Player_Attributes.player_api_id Group by Player.player_api_id')

In [6]:
p1

      player_name              player_api_id overall_rating gk_ratings
1     Patryk Rachwal,18        2625          63             153
2     Diego Mainz              2752          72              53
3     Jose Dorado              2768          75             131
4     Ignacio Gonzalez         2770          74             158
5     Alberto Rey              2790          73             144
6     Javier Jimenez           2796          69             344
7     Pablo Hernandez          2802          82             151
8     Ruben Perez              2805          76             146
9     Ivan Perez               2857          72             150
10    Vicente Sanchez          2862          76             148
11    Gregory Lacombe          2907          68             138
12    Ugur Inceman             2973          72             147
13    David Rivas Rodriguez    2977          82             104
14    Jorge Molina             2983          75             139
15    Sergio Aragones          2984          75             365
16    Alexandre Hauw           3140          69             143
17    Marat Izmailov           3204          81             158
18    Kelly Berville           3263          67             115
19    Abdelmalek Cherrad       3264          62             100
20    Oscar Sanchez            3316          71             108
21    Vincent Euvrard          3329          64             130
22    Luca Belingheri          3377          72             138
23    Aleksander Radosavljevic 3441          71             140
24    Peter Halmosi            3512          75             143
25    Alexandr Kerzhakov       3517          82             149
26    Andrey Arshavin          3520          86             163
27    Lee Wilkie               4747          73             128
28    Boban Grncarov           4863          66              54
29    Iriney                   4902          77             146
30    Tim Clancy               4939          64             117
⋮     ⋮                        ⋮             ⋮              ⋮
11031 Kylian Mbappe Lottin     701154        65             42
11032 Colin Trachsel           703659        51             48
11033 Christopher Nkunku       704523        62             43
11034 Eray Cumart              705484        52             32
11035 Jordan Lyden             706985        58             53
11036 Jonatan Montiel          710807        67             47
11037 Aissa Laidouni           715642        59             61
11038 Sebastien Lamonge        716998        56             46
11039 Felipe Augusto           717248        64             59
11040 Antoine Rabillard        717270        61             56
11041 Levi Garcia              717557        64             49
11042 Dorian Caddy             719413        64             54
11043 Charles Traore           720738        55             52
11044 Rafa Soares              721133        70             60
11045 Charly Musonda           722766        71             36
11046 Wanderson Lima           723037        53             54
11047 Dennis van der Heijden   725718        60             54
11048 Cedric Itten             726956        54             41
11049 Christopher McLaughlin   728125        50             49
11050 Justin Hoogma            728414        59             54
11051 Kamil Jozwiak            728478        56             54
11052 Jorge Intima             730065        57             59
11053 Linus Obexer             733787        51             45
11054 Tom Davies               742405        51             56
11055 Charles Pickel           743720        50             53
11056 Greg Taylor              744907        53             57
11057 Francisco Afonso         746419        59             42
11058 Fynn Arkenberg           748432        58             46
11059 Rees Greenwood           750435        60             48
11060 Alexandre Azevedo        750584        58             54

In [7]:
p2=dbGetQuery(con,'select Player_Attributes.player_api_id ,
count(Match.home_player_1) AS Appearances from Player_Attributes Join Match on (Match.home_player_1==Player_Attributes.player_api_id) Group by Player_Attributes.player_api_id Order By 2 desc')

In [8]:
p2

    player_api_id Appearances
1    31432        5106
2    42422        4653
3    42276        4608
4    40604        3894
5    30660        3720
6    27299        3683
7    33764        3475
8    30717        3472
9    26295        3408
10   31465        3384
11   41618        3366
12   41097        3190
13   41466        3075
14   37868        3051
15   32746        2886
16   26168        2856
17  182917        2825
18   27424        2790
19   30859        2772
20  112978        2759
21   39599        2730
22   27358        2700
23   39170        2700
24   41671        2688
25   31293        2682
26   95336        2660
27   10637        2640
28   39477        2625
29  178778        2600
30   35644        2583
⋮   ⋮             ⋮
877  30281        5
878  46130        5
879  52160        5
880  69793        5
881 148297        5
882 166768        5
883 607121        5
884  11716        4
885  26003        4
886  27342        4
887  30850        4
888  33688        4
889  39163        4
890  68482        4
891 110108        4
892 110136        4
893 121488        4
894 361013        4
895 520798        4
896 614867        4
897 655544        4
898 667964        4
899  39354        3
900  95977        3
901 121854        3
902 202616        3
903 243486        3
904 143923        2
905 148311        2
906 277845        2

In [9]:
p2=dbGetQuery(con,'select Player.player_api_id ,
count(*) AS Appearances from Player Join Match on 
(Match.home_player_1=Player.player_api_id 
OR Match.home_player_2=Player.player_api_id 
OR Match.home_player_3=Player.player_api_id 
OR Match.home_player_4=Player.player_api_id 
OR Match.home_player_5=Player.player_api_id 
OR Match.home_player_6=Player.player_api_id 
OR Match.home_player_7=Player.player_api_id 
OR Match.home_player_8=Player.player_api_id 
OR Match.home_player_9=Player.player_api_id 
OR Match.home_player_10=Player.player_api_id 
OR Match.home_player_11=Player.player_api_id 
OR Match.away_player_1=Player.player_api_id 
OR Match.away_player_2=Player.player_api_id 
OR Match.away_player_3=Player.player_api_id 
OR Match.away_player_4=Player.player_api_id 
OR Match.away_player_5=Player.player_api_id 
OR Match.away_player_6=Player.player_api_id 
OR Match.away_player_7=Player.player_api_id 
OR Match.away_player_8=Player.player_api_id 
OR Match.away_player_9=Player.player_api_id 
OR Match.away_player_10=Player.player_api_id
OR Match.away_player_11=Player.player_api_id) 
Group by Player.player_api_id Order by 2 desc ')

In [10]:
p2

      player_api_id Appearances
1     31293         300
2     41097         294
3     33764         286
4     42422         286
5     26295         282
6     31465         282
7     31432         275
8     26168         268
9     26399         262
10    94550         260
11    30893         259
12    23782         258
13    38433         257
14    41658         257
15    27299         255
16    32575         254
17    23792         253
18    40695         253
19    42276         253
20    56678         252
21    24846         251
22    30859         251
23    38424         250
24    30660         249
25    30981         249
26    32569         248
27    39477         247
28    41466         247
29    30907         245
30    34447         245
⋮     ⋮             ⋮
11031 661509        1
11032 662818        1
11033 664961        1
11034 667786        1
11035 667952        1
11036 667964        1
11037 667970        1
11038 670927        1
11039 671518        1
11040 674492        1
11041 675088        1
11042 680031        1
11043 684723        1
11044 687572        1
11045 689987        1
11046 690290        1
11047 703659        1
11048 710807        1
11049 715642        1
11050 716998        1
11051 717270        1
11052 725718        1
11053 728414        1
11054 728478        1
11055 730065        1
11056 742405        1
11057 743720        1
11058 744907        1
11059 750435        1
11060 750584        1

In [11]:
p3=dbGetQuery(con,'select Player.player_api_id ,
count(DISTINCT league_id) AS leagues from Match Join Player on 
(Match.home_player_1=Player.player_api_id 
OR Match.home_player_2=Player.player_api_id 
OR Match.home_player_3=Player.player_api_id 
OR Match.home_player_4=Player.player_api_id 
OR Match.home_player_5=Player.player_api_id 
OR Match.home_player_6=Player.player_api_id 
OR Match.home_player_7=Player.player_api_id 
OR Match.home_player_8=Player.player_api_id 
OR Match.home_player_9=Player.player_api_id 
OR Match.home_player_10=Player.player_api_id 
OR Match.home_player_11=Player.player_api_id 
OR Match.away_player_1=Player.player_api_id 
OR Match.away_player_2=Player.player_api_id 
OR Match.away_player_3=Player.player_api_id 
OR Match.away_player_4=Player.player_api_id 
OR Match.away_player_5=Player.player_api_id 
OR Match.away_player_6=Player.player_api_id 
OR Match.away_player_7=Player.player_api_id 
OR Match.away_player_8=Player.player_api_id 
OR Match.away_player_9=Player.player_api_id 
OR Match.away_player_10=Player.player_api_id
OR Match.away_player_11=Player.player_api_id) 
Group by Player.player_api_id Order by 2 desc ')

In [12]:
p3

      player_api_id leagues
1      42119        6
2     116750        5
3     178538        5
4      22543        4
5      24123        4
6      25816        4
7      26434        4
8      26489        4
9      26675        4
10     30477        4
11     30692        4
12     30841        4
13     30890        4
14     30918        4
15     31294        4
16     31300        4
17     32937        4
18     33074        4
19     36784        4
20     38229        4
21     38369        4
22     38700        4
23     38795        4
24     40004        4
25     40165        4
26     41877        4
27     46509        4
28     47547        4
29     71353        4
30     93484        4
⋮     ⋮             ⋮
11031 701154        1
11032 703659        1
11033 704523        1
11034 705484        1
11035 706985        1
11036 710807        1
11037 715642        1
11038 716998        1
11039 717248        1
11040 717270        1
11041 717557        1
11042 719413        1
11043 720738        1
11044 721133        1
11045 722766        1
11046 723037        1
11047 725718        1
11048 726956        1
11049 728125        1
11050 728414        1
11051 728478        1
11052 730065        1
11053 733787        1
11054 742405        1
11055 743720        1
11056 744907        1
11057 746419        1
11058 748432        1
11059 750435        1
11060 750584        1

In [13]:
new =merge(p1,p2,by="player_api_id")

In [14]:
new

      player_api_id player_name              overall_rating gk_ratings
1     2625          Patryk Rachwal,18        63             153
2     2752          Diego Mainz              72              53
3     2768          Jose Dorado              75             131
4     2770          Ignacio Gonzalez         74             158
5     2790          Alberto Rey              73             144
6     2796          Javier Jimenez           69             344
7     2802          Pablo Hernandez          82             151
8     2805          Ruben Perez              76             146
9     2857          Ivan Perez               72             150
10    2862          Vicente Sanchez          76             148
11    2907          Gregory Lacombe          68             138
12    2973          Ugur Inceman             72             147
13    2977          David Rivas Rodriguez    82             104
14    2983          Jorge Molina             75             139
15    2984          Sergio Aragones          75             365
16    3140          Alexandre Hauw           69             143
17    3204          Marat Izmailov           81             158
18    3263          Kelly Berville           67             115
19    3264          Abdelmalek Cherrad       62             100
20    3316          Oscar Sanchez            71             108
21    3329          Vincent Euvrard          64             130
22    3377          Luca Belingheri          72             138
23    3441          Aleksander Radosavljevic 71             140
24    3512          Peter Halmosi            75             143
25    3517          Alexandr Kerzhakov       82             149
26    3520          Andrey Arshavin          86             163
27    4747          Lee Wilkie               73             128
28    4863          Boban Grncarov           66              54
29    4902          Iriney                   77             146
30    4939          Tim Clancy               64             117
⋮     ⋮             ⋮                        ⋮              ⋮
11031 701154        Kylian Mbappe Lottin     65             42
11032 703659        Colin Trachsel           51             48
11033 704523        Christopher Nkunku       62             43
11034 705484        Eray Cumart              52             32
11035 706985        Jordan Lyden             58             53
11036 710807        Jonatan Montiel          67             47
11037 715642        Aissa Laidouni           59             61
11038 716998        Sebastien Lamonge        56             46
11039 717248        Felipe Augusto           64             59
11040 717270        Antoine Rabillard        61             56
11041 717557        Levi Garcia              64             49
11042 719413        Dorian Caddy             64             54
11043 720738        Charles Traore           55             52
11044 721133        Rafa Soares              70             60
11045 722766        Charly Musonda           71             36
11046 723037        Wanderson Lima           53             54
11047 725718        Dennis van der Heijden   60             54
11048 726956        Cedric Itten             54             41
11049 728125        Christopher McLaughlin   50             49
11050 728414        Justin Hoogma            59             54
11051 728478        Kamil Jozwiak            56             54
11052 730065        Jorge Intima             57             59
11053 733787        Linus Obexer             51             45
11054 742405        Tom Davies               51             56
11055 743720        Charles Pickel           50             53
11056 744907        Greg Taylor              53             57
11057 746419        Francisco Afonso         59             42
11058 748432        Fynn Arkenberg           58             46
11059 750435        Rees Greenwood           60             48
11060 750584        Alexandre Azevedo        58             54
      Appearances
1      90
2      81
3      71
4      16
5      50
6       1
7     144
8     131
9       3
10     17
11      6
12     16
13      5
14     71
15     38
16     42
17     42
18     19
19      1
20      6
21     85
22      1
23     74
24      4
25     17
26     70
27     36
28     25
29     68
30     97
⋮     ⋮
11031  2
11032  1
11033  4
11034  4
11035  2
11036  1
11037  1
11038  1
11039  4
11040  1
11041  4
11042  3
11043  5
11044 15
11045 13
11046  7
11047  1
11048  4
11049  2
11050  1
11051  1
11052  1
11053  2
11054  1
11055  1
11056  1
11057  2
11058  2
11059  1
11060  1

In [15]:
new1=merge(new,p3,by="player_api_id")
head(new1)

  player_api_id player_name       overall_rating gk_ratings Appearances leagues
1 2625          Patryk Rachwal,18 63             153        90          1
2 2752          Diego Mainz       72              53        81          1
3 2768          Jose Dorado       75             131        71          1
4 2770          Ignacio Gonzalez  74             158        16          2
5 2790          Alberto Rey       73             144        50          1
6 2796          Javier Jimenez    69             344         1          1

In [16]:
write.csv(new1,file="player.csv")

In [17]:
player_read=read.csv("player.csv")
player_read

      X     player_api_id player_name              overall_rating gk_ratings
1      1    2625          Patryk Rachwal,18        63             153
2      2    2752          Diego Mainz              72              53
3      3    2768          Jose Dorado              75             131
4      4    2770          Ignacio Gonzalez         74             158
5      5    2790          Alberto Rey              73             144
6      6    2796          Javier Jimenez           69             344
7      7    2802          Pablo Hernandez          82             151
8      8    2805          Ruben Perez              76             146
9      9    2857          Ivan Perez               72             150
10    10    2862          Vicente Sanchez          76             148
11    11    2907          Gregory Lacombe          68             138
12    12    2973          Ugur Inceman             72             147
13    13    2977          David Rivas Rodriguez    82             104
14    14    2983          Jorge Molina             75             139
15    15    2984          Sergio Aragones          75             365
16    16    3140          Alexandre Hauw           69             143
17    17    3204          Marat Izmailov           81             158
18    18    3263          Kelly Berville           67             115
19    19    3264          Abdelmalek Cherrad       62             100
20    20    3316          Oscar Sanchez            71             108
21    21    3329          Vincent Euvrard          64             130
22    22    3377          Luca Belingheri          72             138
23    23    3441          Aleksander Radosavljevic 71             140
24    24    3512          Peter Halmosi            75             143
25    25    3517          Alexandr Kerzhakov       82             149
26    26    3520          Andrey Arshavin          86             163
27    27    4747          Lee Wilkie               73             128
28    28    4863          Boban Grncarov           66              54
29    29    4902          Iriney                   77             146
30    30    4939          Tim Clancy               64             117
⋮     ⋮     ⋮             ⋮                        ⋮              ⋮
11031 11031 701154        Kylian Mbappe Lottin     65             42
11032 11032 703659        Colin Trachsel           51             48
11033 11033 704523        Christopher Nkunku       62             43
11034 11034 705484        Eray Cumart              52             32
11035 11035 706985        Jordan Lyden             58             53
11036 11036 710807        Jonatan Montiel          67             47
11037 11037 715642        Aissa Laidouni           59             61
11038 11038 716998        Sebastien Lamonge        56             46
11039 11039 717248        Felipe Augusto           64             59
11040 11040 717270        Antoine Rabillard        61             56
11041 11041 717557        Levi Garcia              64             49
11042 11042 719413        Dorian Caddy             64             54
11043 11043 720738        Charles Traore           55             52
11044 11044 721133        Rafa Soares              70             60
11045 11045 722766        Charly Musonda           71             36
11046 11046 723037        Wanderson Lima           53             54
11047 11047 725718        Dennis van der Heijden   60             54
11048 11048 726956        Cedric Itten             54             41
11049 11049 728125        Christopher McLaughlin   50             49
11050 11050 728414        Justin Hoogma            59             54
11051 11051 728478        Kamil Jozwiak            56             54
11052 11052 730065        Jorge Intima             57             59
11053 11053 733787        Linus Obexer             51             45
11054 11054 742405        Tom Davies               51             56
11055 11055 743720        Charles Pickel           50             53
11056 11056 744907        Greg Taylor              53             57
11057 11057 746419        Francisco Afonso         59             42
11058 11058 748432        Fynn Arkenberg           58             46
11059 11059 750435        Rees Greenwood           60             48
11060 11060 750584        Alexandre Azevedo        58             54
      Appearances leagues
1      90         1
2      81         1
3      71         1
4      16         2
5      50         1
6       1         1
7     144         2
8     131         1
9       3         1
10     17         1
11      6         1
12     16         1
13      5         1
14     71         1
15     38         1
16     42         1
17     42         1
18     19         1
19      1         1
20      6         1
21     85         1
22      1         1
23     74         1
24      4         1
25     17         1
26     70         1
27     36         1
28     25         1
29     68         1
30     97         1
⋮     ⋮           ⋮
11031  2          1
11032  1          1
11033  4          1
11034  4          1
11035  2          1
11036  1          1
11037  1          1
11038  1          1
11039  4          1
11040  1          1
11041  4          1
11042  3          1
11043  5          1
11044 15          1
11045 13          1
11046  7          1
11047  1          1
11048  4          1
11049  2          1
11050  1          1
11051  1          1
11052  1          1
11053  2          1
11054  1          1
11055  1          1
11056  1          1
11057  2          1
11058  2          1
11059  1          1
11060  1          1

In [3]:
t1=dbGetQuery(con, 'select
                    Team.team_api_id ,Team.team_long_name ,
                    MAX(IFNULL(Team_Attributes.buildUpPlaySpeed,0))+MAX(IFNULL(Team_Attributes.buildUpPlayDribbling,0))+MAX(IFNULL(Team_Attributes.buildUpPlayPassing,0))as BuildUpPlay,
                    MAX(IFNULL(Team_Attributes.chanceCreationPassing,0))+MAX(IFNULL(TEam_Attributes.chanceCreationCrossing,0))+MAX(IFNULL(Team_Attributes.chanceCreationShooting,0)) as ChanceCreation,
                    MAX(IFNULL(Team_Attributes.defencePressure,0))+MAX(IFNULL(Team_Attributes.defenceAggression,0))+MAX(IFNULL(Team_Attributes.defenceTeamWidth,0)) as defence
                    from Team JOIN Team_Attributes ON Team.team_api_id=Team_Attributes.team_api_id group by Team.team_api_id order by 1 asc')

In [5]:

t1

    team_api_id team_long_name          BuildUpPlay ChanceCreation defence
1    8178       Bayer 04 Leverkusen     158         217            212
2    1957       Jagiellonia Białystok   189         165            210
3    7794       SC Bastia               180         162            210
4    8021       Zagłębie Lubin          164         203            210
5    8197       Leicester City          181         209            210
6    8344       Cardiff City            178         210            210
7    8350       1. FC Kaiserslautern    175         194            210
8    8466       Southampton             166         205            210
9    8481       AS Nancy-Lorraine       162         197            210
10   8483       Blackpool               186         205            210
11   8521       Stade Brestois 29       175         181            210
12   8602       Wolverhampton Wanderers 176         213            210
13   8658       Birmingham City         188         218            210
14   8659       West Bromwich Albion    164         200            210
15   8667       Hull City               165         196            210
16   8678       Bournemouth             184         200            210
17   9831       OGC Nice                201         191            210
18   9847       Paris Saint-Germain     185         195            210
19   9851       Stade Rennais FC        172         200            210
20   9904       Hannover 96             203         182            210
21   9986       Sporting Charleroi      160         158            210
22   9993       Beerschot AC            110         185            210
23  10001       KVC Westerlo            158         181            210
24  10003       Swansea City            180         210            210
25  10172       Queens Park Rangers     179         210            210
26  10249       Montpellier Hérault SC  177         175            210
27   8697       SV Werder Bremen        188         216            208
28  10189       FC Schalke 04           176         204            207
29   8398       FC Energie Cottbus      166         194            206
30   9817       Watford                 183         205            206
⋮   ⋮           ⋮                       ⋮           ⋮              ⋮
259   8234      FC Ingolstadt 04        168         159            145
260   8426      Partick Thistle F.C.    145         162            145
261   9761      NAC Breda               166         155            145
262  10191      FC Thun                 156         179            145
263   8027      Zawisza Bydgoszcz       145         168            143
264   8649      Ross County FC          157         157            143
265   8372      SD Eibar                165         179            142
266   8690      Reggio Calabria         166         201            142
267  10242      ES Troyes AC            148         151            142
268   6433      Go Ahead Eagles         169         132            141
269   9941      Toulouse FC             191         187            141
270   9837      Stade de Reims          169         175            140
271   9996      Royal Excel Mouscron    150         150            140
272 274581      Royal Excel Mouscron    150         150            140
273   7788      SC Cambuur              141         159            138
274   8348      Moreirense FC           139         144            138
275   9998      RAEC Mons               160         168            138
276   1773      Oud-Heverlee Leuven     153         157            137
277   9807      CF Os Belenenses        157         160            135
278   7869      Córdoba CF              159         186            133
279   8573      KV Oostende             155         140            133
280   9824      FC Vaduz                141         137            133
281   8262      SV Darmstadt 98         179         174            129
282   6547      FC Penafiel             147         146            121
283   9809      Naval 1° de Maio        115         165            121
284   8475      Waasland-Beveren        160         146            114
285 158085      FC Arouca               174         160            113
286  10218      Excelsior               183         174            112
287   6421      Leixões SC               60         165             90
288   8614      Sparta Rotterdam         75         140             90

In [6]:
t3=dbGetQuery(con,'select home_team_api_id AS team_api_id,home_team_goal from Match Union All select away_team_api_id,away_team_goal from Match')

In [7]:
t3

      team_api_id home_team_goal
1      9987       1
2     10000       0
3      9984       0
4      9991       5
5      7947       1
6      8203       1
7      9999       2
8      4049       1
9     10001       1
10     8342       4
11     9985       1
12    10000       0
13     9994       0
14     7947       2
15     8203       1
16     9996       0
17     4049       1
18     9993       1
19     8635       2
20     9998       0
21     9986       2
22     9984       2
23     9991       1
24     9999       1
25     8571       0
26    10001       1
27     9993       1
28     8342       1
29     9987       1
30    10000       2
⋮     ⋮           ⋮
51929  7896       1
51930  9931       3
51931 10243       2
51932 10179       1
51933 10191       1
51934 10191       1
51935  7896       1
51936 10190       1
51937 10243       1
51938  9956       3
51939  9931       3
51940 10192       3
51941  9956       2
51942  9824       0
51943 10199       5
51944 10199       1
51945 10190       0
51946 10179       2
51947 10243       1
51948 10192       2
51949 10190       1
51950  9824       0
51951  9956       3
51952 10191       3
51953  7896       0
51954 10191       0
51955 10199       2
51956 10179       0
51957 10243       0
51958  9931       3

In [8]:
t3=dbGetQuery(con,'select home_team_api_id AS team_api_id,home_team_goal from Match Union All 
select away_team_api_id,away_team_goal from Match')

In [9]:
t=sqldf('SELECT team_api_id, SUM(home_team_goal) AS goals FROM t3 GROUP BY team_api_id order by 2 desc')

Warning message:
“Quoted identifiers should have class SQL, use DBI::SQL() if the caller performs the quoting.”

In [10]:
t

    team_api_id goals
1    8634       849
2    8633       843
3    9925       695
4    9823       653
5    8640       652
6    8593       647
7    9931       619
8    8456       606
9    8455       583
10  10260       582
11   9825       573
12   9772       568
13   9847       568
14   9789       551
15   9885       543
16   9773       541
17   8650       531
18   8686       530
19  10192       529
20   9906       524
21   9875       514
22   8611       509
23   9748       497
24   8564       496
25   8636       496
26  10229       492
27  10235       489
28  10267       484
29   8178       483
30   8586       481
⋮   ⋮           ⋮
270   9891      35
271   6269      34
272   8479      34
273   9858      34
274 188163      34
275   8234      33
276 177361      33
277   8344      32
278   4170      31
279   8460      31
280   8550      31
281   8295      30
282   8398      30
283   8690      30
284   9746      30
285   6547      29
286   9765      29
287   9776      29
288   9912      29
289   6351      28
290   8549      28
291   4064      27
292   6367      27
293   9878      27
294   8357      26
295  10213      26
296   7992      25
297   6631      24
298   7869      22
299 108893      21

In [11]:
team=merge(t1,t,by='team_api_id')
#team=arrange(team,desc(chanceCreation))
team

    team_api_id team_long_name           BuildUpPlay ChanceCreation defence
1   1601        Ruch Chorzów             156         205            175
2   1773        Oud-Heverlee Leuven      153         157            137
3   1957        Jagiellonia Białystok    189         165            210
4   2033        S.C. Olhanense           182         178            155
5   2182        Lech Poznań              179         208            181
6   2183        P. Warszawa               81         210            177
7   2186        Cracovia                 166         210            205
8   4087        Évian Thonon Gaillard FC 177         182            168
9   4170        US Boulogne Cote D'Opale  87         177            200
10  6269        Novara                   185         181            173
11  6351        KAS Eupen                105         160            155
12  6391        GFC Ajaccio              166         179            146
13  6403        FC Paços de Ferreira     153         184            168
14  6413        PEC Zwolle               154         165            181
15  6421        Leixões SC                60         165             90
16  6433        Go Ahead Eagles          169         132            141
17  6493        AC Bellinzona            101         175            151
18  6547        FC Penafiel              147         146            121
19  6631        FC Dordrecht             134         176            164
20  7730        FC Lausanne-Sports       166         172            170
21  7788        SC Cambuur               141         159            138
22  7794        SC Bastia                180         162            210
23  7819        SM Caen                  167         180            205
24  7841        Rio Ave FC               163         190            161
25  7842        Estoril Praia            174         139            150
26  7844        Vitória Guimarães        164         191            182
27  7869        Córdoba CF               159         186            133
28  7878        Granada CF               178         203            171
29  7943        Sassuolo                 188         193            154
30  7955        Neuchâtel Xamax          110         190            150
⋮   ⋮           ⋮                        ⋮           ⋮              ⋮
259  10211      SC Beira Mar              96         165            163
260  10212      CS Marítimo              182         208            148
261  10214      CD Nacional              167         172            161
262  10215      Académica de Coimbra     156         175            162
263  10217      ADO Den Haag             171         188            184
264  10218      Excelsior                183         174            112
265  10219      RKC Waalwijk             142         181            150
266  10228      SC Heerenveen            171         200            183
267  10229      AZ                       166         207            190
268  10233      Genoa                    190         202            172
269  10235      Feyenoord                154         177            161
270  10238      Vitória Setúbal          157         180            150
271  10242      ES Troyes AC             148         151            142
272  10243      FC Zürich                171         175            169
273  10249      Montpellier Hérault SC   177         175            210
274  10251      Hibernian                189         200            200
275  10252      Aston Villa              179         191            178
276  10260      Manchester United        166         207            172
277  10261      Newcastle United         187         195            172
278  10264      SC Braga                 156         187            150
279  10265      Wisła Kraków             167         197            205
280  10267      Valencia CF              127         186            175
281  10268      Elche CF                 180         177            159
282  10269      VfB Stuttgart            184         200            181
283  10278      Hércules Club de Fútbol  156         188            166
284  10281      Real Valladolid          164         193            176
285 108893      AC Arles-Avignon         169         141            159
286 158085      FC Arouca                174         160            113
287 208931      Carpi                    191         164            152
288 274581      Royal Excel Mouscron     150         150            140
    goals
1   280
2   126
3   287
4   138
5   372
6   184
7   235
8   180
9    31
10   34
11   28
12   37
13  292
14  204
15   55
16   74
17  128
18   29
19   24
20   99
21  119
22  165
23  220
24  248
25  167
26  300
27   22
28  179
29  141
30  171
⋮   ⋮
259  93
260 316
261 332
262 240
263 366
264 154
265 153
266 470
267 492
268 392
269 489
270 238
271  71
272 468
273 344
274 259
275 335
276 582
277 324
278 398
279 332
280 484
281  65
282 415
283  36
284 170
285  21
286 101
287  37
288  71

In [12]:
write.csv(team,file='team.csv')

In [13]:
team_read=read.csv("team.csv")
team_read

    X   team_api_id team_long_name           BuildUpPlay ChanceCreation defence
1    1  1601        Ruch Chorzów             156         205            175
2    2  1773        Oud-Heverlee Leuven      153         157            137
3    3  1957        Jagiellonia Białystok    189         165            210
4    4  2033        S.C. Olhanense           182         178            155
5    5  2182        Lech Poznań              179         208            181
6    6  2183        P. Warszawa               81         210            177
7    7  2186        Cracovia                 166         210            205
8    8  4087        Évian Thonon Gaillard FC 177         182            168
9    9  4170        US Boulogne Cote D'Opale  87         177            200
10  10  6269        Novara                   185         181            173
11  11  6351        KAS Eupen                105         160            155
12  12  6391        GFC Ajaccio              166         179            146
13  13  6403        FC Paços de Ferreira     153         184            168
14  14  6413        PEC Zwolle               154         165            181
15  15  6421        Leixões SC                60         165             90
16  16  6433        Go Ahead Eagles          169         132            141
17  17  6493        AC Bellinzona            101         175            151
18  18  6547        FC Penafiel              147         146            121
19  19  6631        FC Dordrecht             134         176            164
20  20  7730        FC Lausanne-Sports       166         172            170
21  21  7788        SC Cambuur               141         159            138
22  22  7794        SC Bastia                180         162            210
23  23  7819        SM Caen                  167         180            205
24  24  7841        Rio Ave FC               163         190            161
25  25  7842        Estoril Praia            174         139            150
26  26  7844        Vitória Guimarães        164         191            182
27  27  7869        Córdoba CF               159         186            133
28  28  7878        Granada CF               178         203            171
29  29  7943        Sassuolo                 188         193            154
30  30  7955        Neuchâtel Xamax          110         190            150
⋮   ⋮   ⋮           ⋮                        ⋮           ⋮              ⋮
259 259  10211      SC Beira Mar              96         165            163
260 260  10212      CS Marítimo              182         208            148
261 261  10214      CD Nacional              167         172            161
262 262  10215      Académica de Coimbra     156         175            162
263 263  10217      ADO Den Haag             171         188            184
264 264  10218      Excelsior                183         174            112
265 265  10219      RKC Waalwijk             142         181            150
266 266  10228      SC Heerenveen            171         200            183
267 267  10229      AZ                       166         207            190
268 268  10233      Genoa                    190         202            172
269 269  10235      Feyenoord                154         177            161
270 270  10238      Vitória Setúbal          157         180            150
271 271  10242      ES Troyes AC             148         151            142
272 272  10243      FC Zürich                171         175            169
273 273  10249      Montpellier Hérault SC   177         175            210
274 274  10251      Hibernian                189         200            200
275 275  10252      Aston Villa              179         191            178
276 276  10260      Manchester United        166         207            172
277 277  10261      Newcastle United         187         195            172
278 278  10264      SC Braga                 156         187            150
279 279  10265      Wisła Kraków             167         197            205
280 280  10267      Valencia CF              127         186            175
281 281  10268      Elche CF                 180         177            159
282 282  10269      VfB Stuttgart            184         200            181
283 283  10278      Hércules Club de Fútbol  156         188            166
284 284  10281      Real Valladolid          164         193            176
285 285 108893      AC Arles-Avignon         169         141            159
286 286 158085      FC Arouca                174         160            113
287 287 208931      Carpi                    191         164            152
288 288 274581      Royal Excel Mouscron     150         150            140
    goals
1   280
2   126
3   287
4   138
5   372
6   184
7   235
8   180
9    31
10   34
11   28
12   37
13  292
14  204
15   55
16   74
17  128
18   29
19   24
20   99
21  119
22  165
23  220
24  248
25  167
26  300
27   22
28  179
29  141
30  171
⋮   ⋮
259  93
260 316
261 332
262 240
263 366
264 154
265 153
266 470
267 492
268 392
269 489
270 238
271  71
272 468
273 344
274 259
275 335
276 582
277 324
278 398
279 332
280 484
281  65
282 415
283  36
284 170
285  21
286 101
287  37
288  71

<b><h3>Question 1 :Which are the top 10 players by overall rating?</h3></b>

In [30]:
d<-select(player_read,player_api_id,player_name,overall_rating)
a<-arrange(d,desc(overall_rating))
Ans1<-filter(a,row_number()<=10)
Ans1

   player_api_id player_name       overall_rating
1  30981         Lionel Messi      94
2  30717         Gianluigi Buffon  93
3  30829         Wayne Rooney      93
4  30893         Cristiano Ronaldo 93
5  39854         Xavi Hernandez    92
6  39989         Gregory Coupet    92
7  30626         Thierry Henry     91
8  30627         John Terry        91
9  30657         Iker Casillas     91
10 30723         Alessandro Nesta  91

<b><h3>Question 2 :Which are the top 10 goalkeepers by sum of gk attributes?</h3></b>

In [31]:
d2<-select(player_read,player_api_id,player_name,gk_ratings)
a2=arrange(d2,desc(gk_ratings))
Ans2=filter(a2,row_number()<=10)
Ans2

   player_api_id player_name       gk_ratings
1  30717         Gianluigi Buffon  455
2  30859         Petr Cech         454
3  27299         Manuel Neuer      449
4  39989         Gregory Coupet    447
5  30657         Iker Casillas     446
6  24503         Sebastian Frey    445
7  30989         Julio Cesar       444
8  30726         Edwin van der Sar 442
9  30660         Pepe Reina        436
10 32657         Victor Valdes     436

<b><h3>Question 3:Which are the top 10 players by number of appearances (with any team they played with)?</h3></b>

In [32]:
d3=select(player_read,player_api_id,player_name,Appearances)
a3=arrange(d3,desc(Appearances))
Ans3=filter(a3,row_number()<=10)
Ans3

   player_api_id player_name          Appearances
1  31293         Steve Mandanda       300
2  41097         Stephane Ruffier     294
3  33764         Gorka Iraizoz Moreno 286
4  42422         Samir Handanovic     286
5  26295         Hugo Lloris          282
6  31465         Tim Howard           282
7  31432         Joe Hart             275
8  26168         Cedric Carrasso      268
9  26399         Daniel Congre        262
10 94550         Moussa Sissoko       260

<b><h3>Question 4:Which are the top 10 players by number of leagues they played in?</h3></b>

In [33]:
d4=select(player_read,player_api_id,player_name,leagues)
a4=arrange(d4,desc(leagues))
Ans4=filter(a4,row_number()<=10)
Ans4

   player_api_id player_name           leagues
1   42119        Gelson Fernandes      6
2  116750        Ricky van Wolfswinkel 5
3  178538        Filip Djuricic        5
4   22543        Radamel Falcao        4
5   24123        Jonathan De Guzman    4
6   25816        Almen Abdi            4
7   26434        Ibrahim Afellay       4
8   26489        Edson Braafheid       4
9   26675        Eljero Elia           4
10  30477        Danijel Pranjic       4

<b><h3>Question 5: Which are the top 10 teams by sum of build up play attributes?</h3></b>

In [16]:
d5=select(team_read,team_api_id,team_long_name,BuildUpPlay)
a5=arrange(d5,desc(BuildUpPlay))
Ans5=filter(a5,row_number()<=10)
Ans5

   team_api_id team_long_name     BuildUpPlay
1  8600        Udinese            212
2  8194        Fortuna Düsseldorf 210
3  8245        Korona Kielce      210
4  9804        Torino             209
5  8485        Aberdeen           204
6  8636        Inter              203
7  9904        Hannover 96        203
8  9831        OGC Nice           201
9  8639        LOSC Lille         200
10 9800        St. Mirren         198

<b><h3>Question 6 :Which are the top 10 teams by sum of chance creation attributes?</h3></b>

In [17]:
d6=select(team_read,team_api_id,team_long_name,ChanceCreation)
a6=arrange(d6,desc(ChanceCreation))
Ans6=filter(a6,row_number()<=10)
Ans6

   team_api_id team_long_name         ChanceCreation
1  8592        Olympique de Marseille 227
2  8686        Roma                   222
3  9885        Juventus               222
4  8543        Lazio                  220
5  8548        Rangers                219
6  8658        Birmingham City        218
7  9875        Napoli                 218
8  9906        Atlético Madrid        218
9  8178        Bayer 04 Leverkusen    217
10 8600        Udinese                217

<b><h3>Question 7 : Which are the top 10 teams by sum of defense attributes?</h3></b>

In [18]:
d7=select(team_read,team_api_id,team_long_name,defence)
a7=arrange(d7,desc(defence))
Ans7=filter(a7,row_number()<=10)
Ans7

   team_api_id team_long_name        defence
1  8178        Bayer 04 Leverkusen   212
2  1957        Jagiellonia Białystok 210
3  7794        SC Bastia             210
4  8021        Zagłębie Lubin        210
5  8197        Leicester City        210
6  8344        Cardiff City          210
7  8350        1. FC Kaiserslautern  210
8  8466        Southampton           210
9  8481        AS Nancy-Lorraine     210
10 8483        Blackpool             210

<b><h3>Question 8 : Which are the top 10 teams by number of scored goals?</h3></b>

In [19]:
d8=select(team_read,team_api_id,team_long_name,goals)
a8=arrange(d8,desc(goals))
Ans8=filter(a8,row_number()<=10)
Ans8

   team_api_id team_long_name    goals
1   8634       FC Barcelona      849
2   8633       Real Madrid CF    843
3   9925       Celtic            695
4   9823       FC Bayern Munich  653
5   8640       PSV               652
6   8593       Ajax              647
7   9931       FC Basel          619
8   8456       Manchester City   606
9   8455       Chelsea           583
10 10260       Manchester United 582