In [1]:
library("RSQLite")
library("DBI")
library("data.table")
library("sqldf")
library("dplyr")

Loading required package: gsubfn
Loading required package: proto
Could not load tcltk.  Will use slower R code instead.
------------------------------------------------------------------------------
data.table + dplyr code now lives in dtplyr.
Please library(dtplyr)!
------------------------------------------------------------------------------

Attaching package: ‘dplyr’

The following objects are masked from ‘package:data.table’:

    between, first, last

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [3]:
install.packages("dplyr")

Warning message in install.packages("dplyr"):
“installation of package ‘dplyr’ had non-zero exit status”Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

In [2]:
con=dbConnect(drv=RSQLite::SQLite(),dbname="/home/naina/Downloads/database.sqlite")

In [3]:
tables=dbListTables(con)

In [4]:
print(tables)

[1] "Country"           "League"            "Match"
[4] "Player"            "Player_Attributes" "Team"
[7] "Team_Attributes"   "sqlite_sequence"

In [5]:
p1=dbGetQuery(con,'select Player.player_name, Player.player_api_id,max(Player_Attributes.overall_rating)AS overall_rating,(max(Player_Attributes.gk_diving)+max(Player_Attributes.gk_handling)+max(Player_Attributes.gk_kicking)+max(Player_Attributes.gk_positioning)+max(Player_Attributes.gk_reflexes)) AS gk_ratings from Player, Player_Attributes where Player.player_api_id=Player_Attributes.player_api_id Group by Player.player_api_id')

In [6]:
p1

      player_name              player_api_id overall_rating gk_ratings
1     Patryk Rachwal,18        2625          63             153
2     Diego Mainz              2752          72              53
3     Jose Dorado              2768          75             131
4     Ignacio Gonzalez         2770          74             158
5     Alberto Rey              2790          73             144
6     Javier Jimenez           2796          69             344
7     Pablo Hernandez          2802          82             151
8     Ruben Perez              2805          76             146
9     Ivan Perez               2857          72             150
10    Vicente Sanchez          2862          76             148
11    Gregory Lacombe          2907          68             138
12    Ugur Inceman             2973          72             147
13    David Rivas Rodriguez    2977          82             104
14    Jorge Molina             2983          75             139
15    Sergio Aragones          2984          75             365
16    Alexandre Hauw           3140          69             143
17    Marat Izmailov           3204          81             158
18    Kelly Berville           3263          67             115
19    Abdelmalek Cherrad       3264          62             100
20    Oscar Sanchez            3316          71             108
21    Vincent Euvrard          3329          64             130
22    Luca Belingheri          3377          72             138
23    Aleksander Radosavljevic 3441          71             140
24    Peter Halmosi            3512          75             143
25    Alexandr Kerzhakov       3517          82             149
26    Andrey Arshavin          3520          86             163
27    Lee Wilkie               4747          73             128
28    Boban Grncarov           4863          66              54
29    Iriney                   4902          77             146
30    Tim Clancy               4939          64             117
⋮     ⋮                        ⋮             ⋮              ⋮
11031 Kylian Mbappe Lottin     701154        65             42
11032 Colin Trachsel           703659        51             48
11033 Christopher Nkunku       704523        62             43
11034 Eray Cumart              705484        52             32
11035 Jordan Lyden             706985        58             53
11036 Jonatan Montiel          710807        67             47
11037 Aissa Laidouni           715642        59             61
11038 Sebastien Lamonge        716998        56             46
11039 Felipe Augusto           717248        64             59
11040 Antoine Rabillard        717270        61             56
11041 Levi Garcia              717557        64             49
11042 Dorian Caddy             719413        64             54
11043 Charles Traore           720738        55             52
11044 Rafa Soares              721133        70             60
11045 Charly Musonda           722766        71             36
11046 Wanderson Lima           723037        53             54
11047 Dennis van der Heijden   725718        60             54
11048 Cedric Itten             726956        54             41
11049 Christopher McLaughlin   728125        50             49
11050 Justin Hoogma            728414        59             54
11051 Kamil Jozwiak            728478        56             54
11052 Jorge Intima             730065        57             59
11053 Linus Obexer             733787        51             45
11054 Tom Davies               742405        51             56
11055 Charles Pickel           743720        50             53
11056 Greg Taylor              744907        53             57
11057 Francisco Afonso         746419        59             42
11058 Fynn Arkenberg           748432        58             46
11059 Rees Greenwood           750435        60             48
11060 Alexandre Azevedo        750584        58             54

In [7]:
p2=dbGetQuery(con,'select Player_Attributes.player_api_id ,
count(Match.home_player_1) AS Appearances from Player_Attributes Join Match on (Match.home_player_1==Player_Attributes.player_api_id) Group by Player_Attributes.player_api_id Order By 2 desc')

In [8]:
p2

    player_api_id Appearances
1    31432        5106
2    42422        4653
3    42276        4608
4    40604        3894
5    30660        3720
6    27299        3683
7    33764        3475
8    30717        3472
9    26295        3408
10   31465        3384
11   41618        3366
12   41097        3190
13   41466        3075
14   37868        3051
15   32746        2886
16   26168        2856
17  182917        2825
18   27424        2790
19   30859        2772
20  112978        2759
21   39599        2730
22   27358        2700
23   39170        2700
24   41671        2688
25   31293        2682
26   95336        2660
27   10637        2640
28   39477        2625
29  178778        2600
30   35644        2583
⋮   ⋮             ⋮
877  30281        5
878  46130        5
879  52160        5
880  69793        5
881 148297        5
882 166768        5
883 607121        5
884  11716        4
885  26003        4
886  27342        4
887  30850        4
888  33688        4
889  39163        4
890  68482        4
891 110108        4
892 110136        4
893 121488        4
894 361013        4
895 520798        4
896 614867        4
897 655544        4
898 667964        4
899  39354        3
900  95977        3
901 121854        3
902 202616        3
903 243486        3
904 143923        2
905 148311        2
906 277845        2

In [9]:
p2=dbGetQuery(con,'select Player.player_api_id ,
count(*) AS Appearances from Player Join Match on 
(Match.home_player_1=Player.player_api_id 
OR Match.home_player_2=Player.player_api_id 
OR Match.home_player_3=Player.player_api_id 
OR Match.home_player_4=Player.player_api_id 
OR Match.home_player_5=Player.player_api_id 
OR Match.home_player_6=Player.player_api_id 
OR Match.home_player_7=Player.player_api_id 
OR Match.home_player_8=Player.player_api_id 
OR Match.home_player_9=Player.player_api_id 
OR Match.home_player_10=Player.player_api_id 
OR Match.home_player_11=Player.player_api_id 
OR Match.away_player_1=Player.player_api_id 
OR Match.away_player_2=Player.player_api_id 
OR Match.away_player_3=Player.player_api_id 
OR Match.away_player_4=Player.player_api_id 
OR Match.away_player_5=Player.player_api_id 
OR Match.away_player_6=Player.player_api_id 
OR Match.away_player_7=Player.player_api_id 
OR Match.away_player_8=Player.player_api_id 
OR Match.away_player_9=Player.player_api_id 
OR Match.away_player_10=Player.player_api_id
OR Match.away_player_11=Player.player_api_id) 
Group by Player.player_api_id Order by 2 desc ')

In [10]:
p2

      player_api_id Appearances
1     31293         300
2     41097         294
3     33764         286
4     42422         286
5     26295         282
6     31465         282
7     31432         275
8     26168         268
9     26399         262
10    94550         260
11    30893         259
12    23782         258
13    38433         257
14    41658         257
15    27299         255
16    32575         254
17    23792         253
18    40695         253
19    42276         253
20    56678         252
21    24846         251
22    30859         251
23    38424         250
24    30660         249
25    30981         249
26    32569         248
27    39477         247
28    41466         247
29    30907         245
30    34447         245
⋮     ⋮             ⋮
11031 661509        1
11032 662818        1
11033 664961        1
11034 667786        1
11035 667952        1
11036 667964        1
11037 667970        1
11038 670927        1
11039 671518        1
11040 674492        1
11041 675088        1
11042 680031        1
11043 684723        1
11044 687572        1
11045 689987        1
11046 690290        1
11047 703659        1
11048 710807        1
11049 715642        1
11050 716998        1
11051 717270        1
11052 725718        1
11053 728414        1
11054 728478        1
11055 730065        1
11056 742405        1
11057 743720        1
11058 744907        1
11059 750435        1
11060 750584        1

In [11]:
p3=dbGetQuery(con,'select Player.player_api_id ,
count(DISTINCT league_id) AS leagues from Match Join Player on 
(Match.home_player_1=Player.player_api_id 
OR Match.home_player_2=Player.player_api_id 
OR Match.home_player_3=Player.player_api_id 
OR Match.home_player_4=Player.player_api_id 
OR Match.home_player_5=Player.player_api_id 
OR Match.home_player_6=Player.player_api_id 
OR Match.home_player_7=Player.player_api_id 
OR Match.home_player_8=Player.player_api_id 
OR Match.home_player_9=Player.player_api_id 
OR Match.home_player_10=Player.player_api_id 
OR Match.home_player_11=Player.player_api_id 
OR Match.away_player_1=Player.player_api_id 
OR Match.away_player_2=Player.player_api_id 
OR Match.away_player_3=Player.player_api_id 
OR Match.away_player_4=Player.player_api_id 
OR Match.away_player_5=Player.player_api_id 
OR Match.away_player_6=Player.player_api_id 
OR Match.away_player_7=Player.player_api_id 
OR Match.away_player_8=Player.player_api_id 
OR Match.away_player_9=Player.player_api_id 
OR Match.away_player_10=Player.player_api_id
OR Match.away_player_11=Player.player_api_id) 
Group by Player.player_api_id Order by 2 desc ')

In [12]:
p3

      player_api_id leagues
1      42119        6
2     116750        5
3     178538        5
4      22543        4
5      24123        4
6      25816        4
7      26434        4
8      26489        4
9      26675        4
10     30477        4
11     30692        4
12     30841        4
13     30890        4
14     30918        4
15     31294        4
16     31300        4
17     32937        4
18     33074        4
19     36784        4
20     38229        4
21     38369        4
22     38700        4
23     38795        4
24     40004        4
25     40165        4
26     41877        4
27     46509        4
28     47547        4
29     71353        4
30     93484        4
⋮     ⋮             ⋮
11031 701154        1
11032 703659        1
11033 704523        1
11034 705484        1
11035 706985        1
11036 710807        1
11037 715642        1
11038 716998        1
11039 717248        1
11040 717270        1
11041 717557        1
11042 719413        1
11043 720738        1
11044 721133        1
11045 722766        1
11046 723037        1
11047 725718        1
11048 726956        1
11049 728125        1
11050 728414        1
11051 728478        1
11052 730065        1
11053 733787        1
11054 742405        1
11055 743720        1
11056 744907        1
11057 746419        1
11058 748432        1
11059 750435        1
11060 750584        1

In [13]:
new =merge(p1,p2,by="player_api_id")

In [14]:
new

      player_api_id player_name              overall_rating gk_ratings
1     2625          Patryk Rachwal,18        63             153
2     2752          Diego Mainz              72              53
3     2768          Jose Dorado              75             131
4     2770          Ignacio Gonzalez         74             158
5     2790          Alberto Rey              73             144
6     2796          Javier Jimenez           69             344
7     2802          Pablo Hernandez          82             151
8     2805          Ruben Perez              76             146
9     2857          Ivan Perez               72             150
10    2862          Vicente Sanchez          76             148
11    2907          Gregory Lacombe          68             138
12    2973          Ugur Inceman             72             147
13    2977          David Rivas Rodriguez    82             104
14    2983          Jorge Molina             75             139
15    2984          Sergio Aragones          75             365
16    3140          Alexandre Hauw           69             143
17    3204          Marat Izmailov           81             158
18    3263          Kelly Berville           67             115
19    3264          Abdelmalek Cherrad       62             100
20    3316          Oscar Sanchez            71             108
21    3329          Vincent Euvrard          64             130
22    3377          Luca Belingheri          72             138
23    3441          Aleksander Radosavljevic 71             140
24    3512          Peter Halmosi            75             143
25    3517          Alexandr Kerzhakov       82             149
26    3520          Andrey Arshavin          86             163
27    4747          Lee Wilkie               73             128
28    4863          Boban Grncarov           66              54
29    4902          Iriney                   77             146
30    4939          Tim Clancy               64             117
⋮     ⋮             ⋮                        ⋮              ⋮
11031 701154        Kylian Mbappe Lottin     65             42
11032 703659        Colin Trachsel           51             48
11033 704523        Christopher Nkunku       62             43
11034 705484        Eray Cumart              52             32
11035 706985        Jordan Lyden             58             53
11036 710807        Jonatan Montiel          67             47
11037 715642        Aissa Laidouni           59             61
11038 716998        Sebastien Lamonge        56             46
11039 717248        Felipe Augusto           64             59
11040 717270        Antoine Rabillard        61             56
11041 717557        Levi Garcia              64             49
11042 719413        Dorian Caddy             64             54
11043 720738        Charles Traore           55             52
11044 721133        Rafa Soares              70             60
11045 722766        Charly Musonda           71             36
11046 723037        Wanderson Lima           53             54
11047 725718        Dennis van der Heijden   60             54
11048 726956        Cedric Itten             54             41
11049 728125        Christopher McLaughlin   50             49
11050 728414        Justin Hoogma            59             54
11051 728478        Kamil Jozwiak            56             54
11052 730065        Jorge Intima             57             59
11053 733787        Linus Obexer             51             45
11054 742405        Tom Davies               51             56
11055 743720        Charles Pickel           50             53
11056 744907        Greg Taylor              53             57
11057 746419        Francisco Afonso         59             42
11058 748432        Fynn Arkenberg           58             46
11059 750435        Rees Greenwood           60             48
11060 750584        Alexandre Azevedo        58             54
      Appearances
1      90
2      81
3      71
4      16
5      50
6       1
7     144
8     131
9       3
10     17
11      6
12     16
13      5
14     71
15     38
16     42
17     42
18     19
19      1
20      6
21     85
22      1
23     74
24      4
25     17
26     70
27     36
28     25
29     68
30     97
⋮     ⋮
11031  2
11032  1
11033  4
11034  4
11035  2
11036  1
11037  1
11038  1
11039  4
11040  1
11041  4
11042  3
11043  5
11044 15
11045 13
11046  7
11047  1
11048  4
11049  2
11050  1
11051  1
11052  1
11053  2
11054  1
11055  1
11056  1
11057  2
11058  2
11059  1
11060  1

In [15]:
new1=merge(new,p3,by="player_api_id")
head(new1)

  player_api_id player_name       overall_rating gk_ratings Appearances leagues
1 2625          Patryk Rachwal,18 63             153        90          1
2 2752          Diego Mainz       72              53        81          1
3 2768          Jose Dorado       75             131        71          1
4 2770          Ignacio Gonzalez  74             158        16          2
5 2790          Alberto Rey       73             144        50          1
6 2796          Javier Jimenez    69             344         1          1

In [16]:
write.csv(new1,file="player.csv")

In [17]:
player_read=read.csv("player.csv")
player_read

      X     player_api_id player_name              overall_rating gk_ratings
1      1    2625          Patryk Rachwal,18        63             153
2      2    2752          Diego Mainz              72              53
3      3    2768          Jose Dorado              75             131
4      4    2770          Ignacio Gonzalez         74             158
5      5    2790          Alberto Rey              73             144
6      6    2796          Javier Jimenez           69             344
7      7    2802          Pablo Hernandez          82             151
8      8    2805          Ruben Perez              76             146
9      9    2857          Ivan Perez               72             150
10    10    2862          Vicente Sanchez          76             148
11    11    2907          Gregory Lacombe          68             138
12    12    2973          Ugur Inceman             72             147
13    13    2977          David Rivas Rodriguez    82             104
14    14    2983          Jorge Molina             75             139
15    15    2984          Sergio Aragones          75             365
16    16    3140          Alexandre Hauw           69             143
17    17    3204          Marat Izmailov           81             158
18    18    3263          Kelly Berville           67             115
19    19    3264          Abdelmalek Cherrad       62             100
20    20    3316          Oscar Sanchez            71             108
21    21    3329          Vincent Euvrard          64             130
22    22    3377          Luca Belingheri          72             138
23    23    3441          Aleksander Radosavljevic 71             140
24    24    3512          Peter Halmosi            75             143
25    25    3517          Alexandr Kerzhakov       82             149
26    26    3520          Andrey Arshavin          86             163
27    27    4747          Lee Wilkie               73             128
28    28    4863          Boban Grncarov           66              54
29    29    4902          Iriney                   77             146
30    30    4939          Tim Clancy               64             117
⋮     ⋮     ⋮             ⋮                        ⋮              ⋮
11031 11031 701154        Kylian Mbappe Lottin     65             42
11032 11032 703659        Colin Trachsel           51             48
11033 11033 704523        Christopher Nkunku       62             43
11034 11034 705484        Eray Cumart              52             32
11035 11035 706985        Jordan Lyden             58             53
11036 11036 710807        Jonatan Montiel          67             47
11037 11037 715642        Aissa Laidouni           59             61
11038 11038 716998        Sebastien Lamonge        56             46
11039 11039 717248        Felipe Augusto           64             59
11040 11040 717270        Antoine Rabillard        61             56
11041 11041 717557        Levi Garcia              64             49
11042 11042 719413        Dorian Caddy             64             54
11043 11043 720738        Charles Traore           55             52
11044 11044 721133        Rafa Soares              70             60
11045 11045 722766        Charly Musonda           71             36
11046 11046 723037        Wanderson Lima           53             54
11047 11047 725718        Dennis van der Heijden   60             54
11048 11048 726956        Cedric Itten             54             41
11049 11049 728125        Christopher McLaughlin   50             49
11050 11050 728414        Justin Hoogma            59             54
11051 11051 728478        Kamil Jozwiak            56             54
11052 11052 730065        Jorge Intima             57             59
11053 11053 733787        Linus Obexer             51             45
11054 11054 742405        Tom Davies               51             56
11055 11055 743720        Charles Pickel           50             53
11056 11056 744907        Greg Taylor              53             57
11057 11057 746419        Francisco Afonso         59             42
11058 11058 748432        Fynn Arkenberg           58             46
11059 11059 750435        Rees Greenwood           60             48
11060 11060 750584        Alexandre Azevedo        58             54
      Appearances leagues
1      90         1
2      81         1
3      71         1
4      16         2
5      50         1
6       1         1
7     144         2
8     131         1
9       3         1
10     17         1
11      6         1
12     16         1
13      5         1
14     71         1
15     38         1
16     42         1
17     42         1
18     19         1
19      1         1
20      6         1
21     85         1
22      1         1
23     74         1
24      4         1
25     17         1
26     70         1
27     36         1
28     25         1
29     68         1
30     97         1
⋮     ⋮           ⋮
11031  2          1
11032  1          1
11033  4          1
11034  4          1
11035  2          1
11036  1          1
11037  1          1
11038  1          1
11039  4          1
11040  1          1
11041  4          1
11042  3          1
11043  5          1
11044 15          1
11045 13          1
11046  7          1
11047  1          1
11048  4          1
11049  2          1
11050  1          1
11051  1          1
11052  1          1
11053  2          1
11054  1          1
11055  1          1
11056  1          1
11057  2          1
11058  2          1
11059  1          1
11060  1          1

In [ ]:
t1=dbGetQuery(con,'select Team.team_long_name, Team.team_api_id, max(Team_Attributes.buildPlayUpSpeed)+
              max(Team_Attributes.buildUpPlayDribbling)+
              max(Team_Attributes.buildUpPlayPassing) AS buildUpPlay, max(Team_Attributes.chanceCreationPassing)+
              max(Team_Attributes.chanceCreationCrossing)+ max(Team_Attributes.chanceCreationShooting)AS chanceCreation,
              max(Team_Attributes.defencePressure)+max(Team_Attributes.defenceAggression)+
              max(Team_Attributes.defenceTeamWidth)as defence from Team, Team_Attributes where Team.team_api_id=Team_Attributes.team_api_id
AND Team_Attributes.buildUpPlaySpeed IS NOT NULL 
AND Team_Attributes.buildUpPlayDribbling IS NOT NULL
AND Team_Attributes.buildUpPlayPassing IS NOT NULL
AND Team_Attributes.chanceCreationPassing IS NOT NULL
AND Team_Attributes.chanceCreationCrossing IS NOT NULL 
AND Team_Attributes.chanceCreationShooting IS NOT NULL
AND Team_Attributes.defencePressure IS NOT NULL
AND Team_Attributes.defenceAggression IS NOT NULL
AND Team_Attributes.defenceTeamWidth IS NOT NULL              

Group by Team.team_api_id'
             )

In [21]:
t1=arrange(t1,desc(defence))
t1

    team_long_name             team_api_id buildUpPlay chanceCreation defence
1   FC Barcelona                8634       122         142            191
2   Lazio                       8543       192         220            190
3   FC Bayern Munich            9823       107         115            190
4   Bayer 04 Leverkusen         8178       158         193            187
5   Cagliari                    8529       171         196            187
6   SV Werder Bremen            8697       174         192            186
7   Fiorentina                  8535       121         172            184
8   Burnley                     8191       160         189            183
9   PEC Zwolle                  6413       154         165            181
10  Ajax                        8593       122         152            181
11  Wisła Kraków               10265       136         155            181
12  Vitesse                     8277       160         178            180
13  Borussia Dortmund           9789       174         187            179
14  Leicester City              8197       164         180            178
15  TSG 1899 Hoffenheim         8226       181         189            178
16  Rayo Vallecano              8370       141         135            178
17  FC Porto                    9773       173         190            178
18  VfL Bochum                  9911       180         186            178
19  Real Madrid CF              8633       153         191            177
20  Legia Warszawa              8673       141         167            176
21  RSC Anderlecht              8635       149         160            175
22  Sampdoria                   9882       130         163            175
23  RC Celta de Vigo            9910       176         179            175
24  Athletic Club de Bilbao     8315       131         157            174
25  Sporting CP                 9768       178         147            174
26  Málaga CF                   9864       132         188            174
27  KRC Genk                    9987       148         192            174
28  Empoli                      8534       148         196            173
29  Tottenham Hotspur           8586       133         163            173
30  Napoli                      9875       183         215            173
⋮   ⋮                          ⋮           ⋮           ⋮              ⋮
233 Piast Gliwice                8028      183         169            129
234 SV Darmstadt 98              8262      179         174            129
235 Stade Brestois 29            8521      161         168            129
236 Feyenoord                   10235      154         165            129
237 BSC Young Boys              10192      172         151            128
238 Stade de Reims               9837      155         158            127
239 Genoa                       10233      184         168            127
240 Chelsea                      8455      157         170            126
241 Livorno                      8537      183         142            126
242 Grasshopper Club Zürich      9956      164         152            126
243 Hibernian                   10251      148         139            124
244 Portsmouth                   8462      148         149            123
245 Middlesbrough                8549      148         177            122
246 RCD Espanyol                 8558      146         152            122
247 FC Penafiel                  6547      147         146            121
248 Hull City                    8667      151         170            121
249 SC Braga                    10264      145         166            120
250 Karlsruher SC                8295      164         148            119
251 AJ Auxerre                   8583      168         164            119
252 Roda JC Kerkrade             9803      133         146            118
253 Crystal Palace               9826      174         188            118
254 Cardiff City                 8344      168         154            113
255 FC Arouca                  158085      174         160            113
256 West Ham United              8654      189         173            108
257 Excelsior                   10218      163         136            106
258 S.C. Olhanense               2033      147         134            105
259 Podbeskidzie Bielsko-Biała   8033      193         166            102
260 Waasland-Beveren             8475      132         140             99
261 RKC Waalwijk                10219      142         133             99
262 Fulham                       9879      142         171             98

In [22]:
t3=dbGetQuery(con,'select home_team_api_id AS team_api_id,home_team_goal from Match Union All select away_team_api_id,away_team_goal from Match')

In [23]:
t3

      team_api_id home_team_goal
1      9987       1
2     10000       0
3      9984       0
4      9991       5
5      7947       1
6      8203       1
7      9999       2
8      4049       1
9     10001       1
10     8342       4
11     9985       1
12    10000       0
13     9994       0
14     7947       2
15     8203       1
16     9996       0
17     4049       1
18     9993       1
19     8635       2
20     9998       0
21     9986       2
22     9984       2
23     9991       1
24     9999       1
25     8571       0
26    10001       1
27     9993       1
28     8342       1
29     9987       1
30    10000       2
⋮     ⋮           ⋮
51929  7896       1
51930  9931       3
51931 10243       2
51932 10179       1
51933 10191       1
51934 10191       1
51935  7896       1
51936 10190       1
51937 10243       1
51938  9956       3
51939  9931       3
51940 10192       3
51941  9956       2
51942  9824       0
51943 10199       5
51944 10199       1
51945 10190       0
51946 10179       2
51947 10243       1
51948 10192       2
51949 10190       1
51950  9824       0
51951  9956       3
51952 10191       3
51953  7896       0
51954 10191       0
51955 10199       2
51956 10179       0
51957 10243       0
51958  9931       3

In [24]:
t3=dbGetQuery(con,'select home_team_api_id AS team_api_id,home_team_goal from Match Union All 
select away_team_api_id,away_team_goal from Match')

In [25]:
t=sqldf('SELECT team_api_id, SUM(home_team_goal) AS goals FROM t3 GROUP BY team_api_id order by 2 desc')

Warning message:
“Quoted identifiers should have class SQL, use DBI::SQL() if the caller performs the quoting.”

In [26]:
t

    team_api_id goals
1    8634       849
2    8633       843
3    9925       695
4    9823       653
5    8640       652
6    8593       647
7    9931       619
8    8456       606
9    8455       583
10  10260       582
11   9825       573
12   9772       568
13   9847       568
14   9789       551
15   9885       543
16   9773       541
17   8650       531
18   8686       530
19  10192       529
20   9906       524
21   9875       514
22   8611       509
23   9748       497
24   8564       496
25   8636       496
26  10229       492
27  10235       489
28  10267       484
29   8178       483
30   8586       481
⋮   ⋮           ⋮
270   9891      35
271   6269      34
272   8479      34
273   9858      34
274 188163      34
275   8234      33
276 177361      33
277   8344      32
278   4170      31
279   8460      31
280   8550      31
281   8295      30
282   8398      30
283   8690      30
284   9746      30
285   6547      29
286   9765      29
287   9776      29
288   9912      29
289   6351      28
290   8549      28
291   4064      27
292   6367      27
293   9878      27
294   8357      26
295  10213      26
296   7992      25
297   6631      24
298   7869      22
299 108893      21

In [27]:
team=merge(t1,t,by='team_api_id')
team=arrange(team,desc(chanceCreation))
team

    team_api_id team_long_name           buildUpPlay chanceCreation defence
1   8543        Lazio                    192         220            190
2   9875        Napoli                   183         215            173
3   8658        Birmingham City          174         212            144
4   8636        Inter                    203         203            167
5   8686        Roma                     163         203            141
6   8600        Udinese                  205         199            154
7   9885        Juventus                 121         198            138
8   8429        Hamilton Academical FC   143         197            155
9   8581        Levante UD               178         197            155
10  9790        Hamburger SV             164         197            149
11  2182        Lech Poznań              176         196            171
12  8529        Cagliari                 171         196            187
13  8534        Empoli                   148         196            173
14  8178        Bayer 04 Leverkusen      158         193            187
15  8697        SV Werder Bremen         174         192            186
16  9987        KRC Genk                 148         192            174
17  8485        Aberdeen                 185         191            157
18  8633        Real Madrid CF           153         191            177
19  9847        Paris Saint-Germain      174         191            166
20  9773        FC Porto                 173         190            178
21  8191        Burnley                  160         189            183
22  8226        TSG 1899 Hoffenheim      181         189            178
23  8721        VfL Wolfsburg            192         189            169
24  9804        Torino                   209         189            137
25  8559        Bolton Wanderers         167         188            145
26  9826        Crystal Palace           174         188            118
27  9864        Málaga CF                132         188            174
28  9906        Atlético Madrid          160         188            149
29  7878        Granada CF               178         187            158
30  8030        Lechia Gdańsk            162         187            172
⋮   ⋮           ⋮                        ⋮           ⋮              ⋮
233   8475      Waasland-Beveren         132         140             99
234   8573      KV Oostende              155         140            133
235  10003      Swansea City             149         140            163
236   7842      Estoril Praia            174         139            150
237   8019      Górnik Łęczna            140         139            149
238   8569      GKS Bełchatów            143         139            132
239   9905      1. FSV Mainz 05          178         139            169
240  10251      Hibernian                148         139            124
241   8524      Atalanta                 146         138            151
242   8576      AC Ajaccio               168         138            138
243 108893      AC Arles-Avignon         158         138            158
244   9824      FC Vaduz                 141         137            133
245   8467      St. Johnstone FC         171         136            143
246   8650      Liverpool                176         136            165
247  10218      Excelsior                163         136            106
248   8370      Rayo Vallecano           141         135            178
249   2033      S.C. Olhanense           147         134            105
250   8571      KV Kortrijk              129         134            143
251  10219      RKC Waalwijk             142         133             99
252   6433      Go Ahead Eagles          169         132            141
253   8479      RC Recreativo            148         132            151
254   9857      Bologna                  164         132            132
255  10000      SV Zulte-Waregem         147         131            139
256   9904      Hannover 96              144         129            148
257   8613      Boavista FC              153         128            148
258   9761      NAC Breda                154         128            132
259   9807      CF Os Belenenses         157         128            135
260   9823      FC Bayern Munich         107         115            190
261  10190      FC St. Gallen            146         115            133
262   9788      Borussia Mönchengladbach 116         113            134
    goals
1   417
2   514
3    75
4   496
5   530
6   415
7   543
8   185
9   241
10  344
11  372
12  309
13   86
14  483
15  423
16  348
17  365
18  843
19  568
20  541
21   70
22  400
23  463
24  241
25  181
26  119
27  377
28  524
29  179
30  279
⋮   ⋮
233 105
234 102
235 233
236 167
237  61
238 190
239 320
240 259
241 283
242 116
243  21
244 100
245 308
246 531
247 154
248 247
249 138
250 267
251 153
252  74
253  34
254 263
255 306
256 359
257  51
258 294
259 148
260 653
261 276
262 403

In [28]:
write.csv(team,file='team.csv')

In [29]:
team_read=read.csv("team.csv")
team_read

    X   team_api_id team_long_name           buildUpPlay chanceCreation defence
1    1  8543        Lazio                    192         220            190
2    2  9875        Napoli                   183         215            173
3    3  8658        Birmingham City          174         212            144
4    4  8636        Inter                    203         203            167
5    5  8686        Roma                     163         203            141
6    6  8600        Udinese                  205         199            154
7    7  9885        Juventus                 121         198            138
8    8  8429        Hamilton Academical FC   143         197            155
9    9  8581        Levante UD               178         197            155
10  10  9790        Hamburger SV             164         197            149
11  11  2182        Lech Poznań              176         196            171
12  12  8529        Cagliari                 171         196            187
13  13  8534        Empoli                   148         196            173
14  14  8178        Bayer 04 Leverkusen      158         193            187
15  15  8697        SV Werder Bremen         174         192            186
16  16  9987        KRC Genk                 148         192            174
17  17  8485        Aberdeen                 185         191            157
18  18  8633        Real Madrid CF           153         191            177
19  19  9847        Paris Saint-Germain      174         191            166
20  20  9773        FC Porto                 173         190            178
21  21  8191        Burnley                  160         189            183
22  22  8226        TSG 1899 Hoffenheim      181         189            178
23  23  8721        VfL Wolfsburg            192         189            169
24  24  9804        Torino                   209         189            137
25  25  8559        Bolton Wanderers         167         188            145
26  26  9826        Crystal Palace           174         188            118
27  27  9864        Málaga CF                132         188            174
28  28  9906        Atlético Madrid          160         188            149
29  29  7878        Granada CF               178         187            158
30  30  8030        Lechia Gdańsk            162         187            172
⋮   ⋮   ⋮           ⋮                        ⋮           ⋮              ⋮
233 233   8475      Waasland-Beveren         132         140             99
234 234   8573      KV Oostende              155         140            133
235 235  10003      Swansea City             149         140            163
236 236   7842      Estoril Praia            174         139            150
237 237   8019      Górnik Łęczna            140         139            149
238 238   8569      GKS Bełchatów            143         139            132
239 239   9905      1. FSV Mainz 05          178         139            169
240 240  10251      Hibernian                148         139            124
241 241   8524      Atalanta                 146         138            151
242 242   8576      AC Ajaccio               168         138            138
243 243 108893      AC Arles-Avignon         158         138            158
244 244   9824      FC Vaduz                 141         137            133
245 245   8467      St. Johnstone FC         171         136            143
246 246   8650      Liverpool                176         136            165
247 247  10218      Excelsior                163         136            106
248 248   8370      Rayo Vallecano           141         135            178
249 249   2033      S.C. Olhanense           147         134            105
250 250   8571      KV Kortrijk              129         134            143
251 251  10219      RKC Waalwijk             142         133             99
252 252   6433      Go Ahead Eagles          169         132            141
253 253   8479      RC Recreativo            148         132            151
254 254   9857      Bologna                  164         132            132
255 255  10000      SV Zulte-Waregem         147         131            139
256 256   9904      Hannover 96              144         129            148
257 257   8613      Boavista FC              153         128            148
258 258   9761      NAC Breda                154         128            132
259 259   9807      CF Os Belenenses         157         128            135
260 260   9823      FC Bayern Munich         107         115            190
261 261  10190      FC St. Gallen            146         115            133
262 262   9788      Borussia Mönchengladbach 116         113            134
    goals
1   417
2   514
3    75
4   496
5   530
6   415
7   543
8   185
9   241
10  344
11  372
12  309
13   86
14  483
15  423
16  348
17  365
18  843
19  568
20  541
21   70
22  400
23  463
24  241
25  181
26  119
27  377
28  524
29  179
30  279
⋮   ⋮
233 105
234 102
235 233
236 167
237  61
238 190
239 320
240 259
241 283
242 116
243  21
244 100
245 308
246 531
247 154
248 247
249 138
250 267
251 153
252  74
253  34
254 263
255 306
256 359
257  51
258 294
259 148
260 653
261 276
262 403

<b><h3>Question 1 :Which are the top 10 players by overall rating?</h3></b>

In [30]:
d<-select(player_read,player_api_id,player_name,overall_rating)
a<-arrange(d,desc(overall_rating))
Ans1<-filter(a,row_number()<=10)
Ans1

   player_api_id player_name       overall_rating
1  30981         Lionel Messi      94
2  30717         Gianluigi Buffon  93
3  30829         Wayne Rooney      93
4  30893         Cristiano Ronaldo 93
5  39854         Xavi Hernandez    92
6  39989         Gregory Coupet    92
7  30626         Thierry Henry     91
8  30627         John Terry        91
9  30657         Iker Casillas     91
10 30723         Alessandro Nesta  91

<b><h3>Question 2 :Which are the top 10 goalkeepers by sum of gk attributes?</h3></b>

In [31]:
d2<-select(player_read,player_api_id,player_name,gk_ratings)
a2=arrange(d2,desc(gk_ratings))
Ans2=filter(a2,row_number()<=10)
Ans2

   player_api_id player_name       gk_ratings
1  30717         Gianluigi Buffon  455
2  30859         Petr Cech         454
3  27299         Manuel Neuer      449
4  39989         Gregory Coupet    447
5  30657         Iker Casillas     446
6  24503         Sebastian Frey    445
7  30989         Julio Cesar       444
8  30726         Edwin van der Sar 442
9  30660         Pepe Reina        436
10 32657         Victor Valdes     436

<b><h3>Question 3:Which are the top 10 players by number of appearances (with any team they played with)?</h3></b>

In [32]:
d3=select(player_read,player_api_id,player_name,Appearances)
a3=arrange(d3,desc(Appearances))
Ans3=filter(a3,row_number()<=10)
Ans3

   player_api_id player_name          Appearances
1  31293         Steve Mandanda       300
2  41097         Stephane Ruffier     294
3  33764         Gorka Iraizoz Moreno 286
4  42422         Samir Handanovic     286
5  26295         Hugo Lloris          282
6  31465         Tim Howard           282
7  31432         Joe Hart             275
8  26168         Cedric Carrasso      268
9  26399         Daniel Congre        262
10 94550         Moussa Sissoko       260

<b><h3>Question 4:Which are the top 10 players by number of leagues they played in?</h3></b>

In [33]:
d4=select(player_read,player_api_id,player_name,leagues)
a4=arrange(d4,desc(leagues))
Ans4=filter(a4,row_number()<=10)
Ans4

   player_api_id player_name           leagues
1   42119        Gelson Fernandes      6
2  116750        Ricky van Wolfswinkel 5
3  178538        Filip Djuricic        5
4   22543        Radamel Falcao        4
5   24123        Jonathan De Guzman    4
6   25816        Almen Abdi            4
7   26434        Ibrahim Afellay       4
8   26489        Edson Braafheid       4
9   26675        Eljero Elia           4
10  30477        Danijel Pranjic       4

<b><h3>Question 5: Which are the top 10 teams by sum of build up play attributes?</h3></b>

In [34]:
d5=select(team_read,team_api_id,team_long_name,buildUpPlay)
a5=arrange(d5,desc(buildUpPlay))
Ans5=filter(a5,row_number()<=10)
Ans5

   team_api_id team_long_name             buildUpPlay
1    9804      Torino                     209
2    8600      Udinese                    205
3    8636      Inter                      203
4    8194      Fortuna Düsseldorf         198
5    8033      Podbeskidzie Bielsko-Biała 193
6    8543      Lazio                      192
7    8721      VfL Wolfsburg              192
8    8245      Korona Kielce              192
9  208931      Carpi                      191
10   8024      Widzew Łódź                190